
MAX_SEQUENCE_LENGTH = 30
TRAIN_URL = "https://drive.google.com/file/d/1ND_nNV5Lh2_rf3xcHbvwkKLbY2DmOH09/view?usp=sharing"

PAD_TOKEN_IDX = 0
SOS_TOKEN_IDX = 1
EOS_TOKEN_IDX = 2

EMBEDDING_SIZE = 128
ENCODER_HIDDEN_SIZE = 256
DECODER_HIDDEN_SIZE = 256
BATCH_SIZE = 512
LEARNING_RATE = 1e-3
EPOCHES = 20